### ISSUE TITLE
macOS Sierra

### ISSUE THREAD

**Issue by binarykitchen** [codez/ImportPhotoFolders#15]
Does it work fine for macOS Sierra?

Doesnt look like. When I tried to run for 7k photos only 2k were successfully imported and the rest not due to invalid meta data?

**Comment by excalibur25** [comment]
for me its working under macOS Sierra 10.12.13. Im using SMB share and got the invalid meta data error only one time. After completely restarting the script it was working without any issues. Dont know whats was causing the issue

**Comment by codez** [comment]
I guess the invalid meta data error is caused by Photos and not by this script.
