### ISSUE TITLE
Not all common file extensions

### ISSUE THREAD

**Issue by mstangler** [codez/ImportPhotoFolders#2]
Please add other common supported photo file extensions - for example 
ORF - Olympus raw
NEF - Nikon raw
CRW, CR2 - Canon raw
DNG - Adobe digital negative
...
 https://en.wikipedia.org/wiki/Raw_image_format#Raw_filename_extensions_and_respective_camera_manufacturers

https://support.apple.com/en-us/HT203088

thank you

**Comment by wheresaldo** [comment]
Thank you so much for making this script.  If photo (file) is duplicated in the folder, Apple Photos will display a dialog asking user what to do, which will pause the script and wait for user response.  Can you update the script, so it won't copy duplicated images?  Thank you!

**Comment by codez** [comment]
@wheresaldo: For new features, please open a separate issue instead of commenting on a completely unrelated one. Unfortunately, Apple Photos does not provide an option to not copy duplicates on import. If you would like to have that feature, please contact Apple directly.
