### ISSUE TITLE
Auto-Import Duplicates

### ISSUE THREAD

**Issue by jryant** [codez/ImportPhotoFolders#20]
Is it possible to modify the script to tell Photos to automatically import (or NOT import) all duplicates? This script is fantastic but still requires manual intervention to tell Photos what to do for dups.

**Comment by codez** [comment]
The interface provided by Photos unfortunately does not provide this option.

**Comment by tommylux** [comment]
What does the "check duplicates no" section in the script do? Is this still the case? I want to skip duplicates. Failing to press Skip will time out.

**Comment by codez** [comment]
As far as I figured out, there was no way to tell Photos to skip duplicates. If this has changed, pull requests are very welcome.

**Comment by tommylux** [comment]
I checked out the Automator gui and it looks like you’re right. Only an option to skip the checking.
