### ISSUE TITLE
Great => additional feature : Deleting option

### ISSUE THREAD

**Issue by bolish** [codez/ImportPhotoFolders#4]
Hi, I would like to thank you for this tools, really helps me within my workflow : 
Lightroom => Export to finder => Import to Photos
Then, I would like to propose some additional features or ideas that would really support people having the same need as me (a kind of sync between Lightroom / finder and Photos)

=> Script acting as a syncing. Being able to delete a photo in the library when original picture no more present into the finder folder.
(i.e : for each thumbnail in Photos for which the original picture in the finder folder is missing, delete the thumbnail in Photos)

=> Avoiding the dial box asking if we want to re-import / replace a photo when already existing into Photos. (just don't re-import twice)
(currently, even if I answer "no" to the dial box, the script is still creating a second empty album)

Hope my ideas will interest someone and/or someone could help me into getting this done!!

Once more, thanks for this first part. Regards

**Comment by codez** [comment]
Unfortunately, Photos does not support checking for existing pictures / automatically replacing them via script. You have to contact Apple for this feature first.

**Comment by bolish** [comment]
Hi Thanks for feedback. Without deleting them, do you think that it could be possible to write a script that would gather all Photos photos for which the orignal file is missing (in the finder) into a Photos album or smart album so that I could delete them manually afterwards?

**Comment by bolish** [comment]
second question : for the issue where the script is creating twice the album in Photos when you import an folder that was already imported before, do you think that there is something possible to do / improve?

**Comment by codez** [comment]
I do not know these answers. This script is supposed to just do a one time import. I do not plan to create a full featured synchronisation tool.
