### ISSUE TITLE
Finder Error number -1712

### ISSUE THREAD

**Issue by lzhivkov** [codez/ImportPhotoFolders#6]
Hi,
thank you very much for offering this script, it is a brilliant work!

Unfortunately I'm having some troubles using it: I'm getting a finder error ""Finder got an error: AppleEvent timed out." number -1712".
I'm using the most resent version of El Capitan, my photos are on an external NAS, connection speed is 1 GB. The photos are being imported really slow with the script, if I import a folder manually it goes significantly faster. For example one folder has 11 GB data with approx. 6000 photos in it.
Do you have an idea, what can I do, I would really appreciate it if you can help me.
Thanks

**Comment by codez** [comment]
Sorry, I think this an issue with AppleScripts in general, not something that the import script could tackle on its own.
